# Site
name: "Onshape4FRC"
title: "Onshape4FRC"
description: "Onshape CAD and Design resources to help teach for FRC."
logo: "assets/images/onshape4frc-logo.png"
favicon: "assets/images/favicon.png"
baseurl: ""
google_analytics: "UA-170618487-1"
disqus: "demowebsite"
# mailchimp-list: ''
include: ["_pages"]
permalink: blog/:title/

# Authors
# authors:
#   max:
#     name: Max Westwater
#     display_name: Max Westwater
#     team: 6328/5254
#     avatar: https://www.chiefdelphi.com/user_avatar/www.chiefdelphi.com/maximillian/120/146348_2.png
#     email: maxwestwater@gmail.com
#     cd: maximillian
#     description: "The lead silver medalist."
#   dave:
#     name: Dave Powers
#     display_name: Dave Powers
#     team: 6328
#     avatar: https://www.chiefdelphi.com/user_avatar/www.chiefdelphi.com/davepowers/240/126656_2.png
#     email: dave@littletonrobotics.org
#     cd: davepowers
#     description: "The lead milk consumer."
#   jack:
#     name: Jack Tervay
#     display_name: Jack Tervay
#     team: 6328/2791
#     avatar: https://www.chiefdelphi.com/letter_avatar_proxy/v4/letter/j/5daacb/120.png
#     email: jacktervay@gmail.com
#     cd: jacktervay
#     description: "6328 lead technical mentor."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: blog/page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]

host: 0.0.0.0
